
# ----------------------------------------------------
# Stage 1: Builder (构建环境) - 负责编译代码
# ----------------------------------------------------
FROM node:20.18.0 AS builder

# 解决 CI 环境等待交互
ENV CI=true

# 设置工作目录
WORKDIR /app

# 拷贝 Monorepo 项目以及子项目所需要的文件
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY ./apps/web ./apps/web/
# COPY ./packages ./packages/

# 安装依赖，打包构建
RUN npm install pnpm@10.16.1 -g
RUN pnpm install --frozen-lockfile
RUN pnpm run build:web

# ----------------------------------------------------
# Stage 2: Production (使用 Nginx 服务静态文件)
# ----------------------------------------------------
FROM nginx:alpine

# 移除 Nginx 默认配置
RUN rm /etc/nginx/conf.d/default.conf

# 从宿主机拷贝自定义的 Nginx 配置
COPY ./apps/web/nginx.conf /etc/nginx/conf.d/default.conf

# 从打包临时环境中拷贝编译好的代码
COPY --from=builder /app/apps/web/dist /usr/share/nginx/html

# 暴露端口，前台运行（注意结尾分号，否则抛出错误）
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]