name: APP PUBLISH

on: workflow_dispatch

jobs:
  test_job:
    name: (一) 测试
    uses: ./.github/workflows/actions/ci-test.yml@master
  build_job:
    name: (二) 构建
    needs: test_job
    uses: ./.github/workflows/actions/ci-build.yml@master
  deploy_job:
    name: (三) 部署
    needs: build_job
    uses: ./.github/workflows/actions/cd-deploy.yml@master