name: (Module) CI - Build

on:
  workflow_call:
    inputs:
      docker-registry:
        required: true
        type: string

jobs:
  # build-api:
  #   uses: ./.github/workflows/actions/build.yml
  #   with:
  #     docker-registry: ghcr.io
  #     docker-image-name: stock-api
  #     docker-file: ./apps/api/dockerfile
  #     github-actor: ${{ github.actor }}
  #   secrets:
  #     github-token: ${{ secrets.GITHUB_TOKEN }}
  build-web:
    uses: ./.github/workflows/build.yml
    with:
      docker-registry: ${{ inputs.docker-registry }}/${{ github.repository }}
      docker-image-name: stock-web
      docker-context: .
      docker-file: ./apps/web/dockerfile
      github-actor: ${{ github.actor }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
