name: CI BUILD

on:
  workflow_run:
    workflows: [CI TEST]
    types:
      - completed
    branches: [master]

jobs:
  # build-api:
  #   uses: ./.github/actions/build.yml
  #   with:
  #     docker-registry: ghcr.io
  #     docker-image-name: stock-api
  #     docker-file: ./apps/api/dockerfile
  #     github-actor: ${{ github.actor }}
  #   secrets:
  #     github-token: ${{ secrets.GITHUB_TOKEN }}
  build-web:
    permissions:
      packages: write
      id-token: write
    uses: ./.github/workflows/build.yml
    with:
      docker-registry: ghcr.io
      docker-image-name: stock-web
      docker-context: .
      docker-file: ./apps/web/dockerfile
      github-actor: ${{ github.actor }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
